# Generated by Django 4.2 on 2023-05-03 22:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polish_name', models.TextField(max_length=100, null=True)),
                ('english_name', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('compositions', models.ManyToManyField(blank=True, related_name='compositions', to='base.composition')),
                ('program_pianist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['program_pianist'],
            },
        ),
        migrations.CreateModel(
            name='Pianist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('pianist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('programs', models.ManyToManyField(blank=True, related_name='programs', to='base.program')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_date', models.DateTimeField(default=datetime.datetime(2023, 5, 4, 0, 51, 0, 442982), unique=True)),
                ('concert_pianist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('concert_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.program')),
            ],
            options={
                'ordering': ['concert_date'],
            },
        ),
    ]
