# Generated by Django 4.2 on 2023-05-03 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 0, 51, 38, 445675), unique=True),
        ),
    ]
