# Generated by Django 4.1.7 on 2023-03-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='creating',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='updating',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='systemmessage',
            name='creating',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='systemmessage',
            name='updating',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
