# Generated by Django 4.1.7 on 2023-04-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_chopinpieces_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='english_name',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='composition',
            name='polish_name',
            field=models.TextField(default='', max_length=150),
        ),
    ]
