# Generated by Django 4.1.7 on 2023-04-13 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_composition_english_name_composition_polish_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChopinPieces',
        ),
        migrations.RemoveField(
            model_name='pianist',
            name='program',
        ),
        migrations.AddField(
            model_name='composition',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.program'),
        ),
    ]
