# Generated by Django 4.1.7 on 2023-04-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_chopinpieces_remove_pianist_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='english_name',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='polish_name',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
