# Generated by Django 4.1.7 on 2023-04-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_program_pianist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='program',
        ),
        migrations.AddField(
            model_name='program',
            name='compositions',
            field=models.ManyToManyField(to='base.composition'),
        ),
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='english_name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='polish_name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
