# Generated by Django 4.1.7 on 2023-04-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_composition_program_program_compositions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='compositions',
        ),
        migrations.RemoveField(
            model_name='program',
            name='pianist',
        ),
        migrations.AddField(
            model_name='composition',
            name='programs',
            field=models.ManyToManyField(to='base.program'),
        ),
        migrations.AddField(
            model_name='pianist',
            name='programs',
            field=models.ManyToManyField(to='base.program'),
        ),
    ]
