# Generated by Django 4.1.7 on 2023-04-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_program_compositions_remove_program_pianist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='programs',
        ),
        migrations.AddField(
            model_name='program',
            name='compositions',
            field=models.ManyToManyField(blank=True, to='base.composition'),
        ),
        migrations.AlterField(
            model_name='pianist',
            name='programs',
            field=models.ManyToManyField(blank=True, to='base.program'),
        ),
    ]
