# Generated by Django 4.1.7 on 2023-04-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_composition_programs_program_compositions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pianist',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='programs', to='base.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='compositions',
            field=models.ManyToManyField(blank=True, related_name='compositions', to='base.composition'),
        ),
    ]
