# Generated by Django 4.1.7 on 2023-04-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_pianist_next_concert_program_concert_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='concert_date',
            new_name='date',
        ),
    ]
