# Generated by Django 4.1.7 on 2023-04-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_program_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='date',
        ),
    ]
