# Generated by Django 4.1.7 on 2023-04-19 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0020_program_pianist_alter_pianist_pianist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='pianist',
        ),
        migrations.AddField(
            model_name='program',
            name='pianist',
            field=models.ManyToManyField(blank=True, related_name='program_pianist', to=settings.AUTH_USER_MODEL),
        ),
    ]
