# Generated by Django 4.1.7 on 2023-04-20 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0022_rename_pianist_program_program_pianist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_pianist',
        ),
        migrations.AddField(
            model_name='program',
            name='program_pianist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
