# Generated by Django 4.1.7 on 2023-04-20 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_program_program_pianist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 0, 39, 5, 279716)),
        ),
    ]
