# Generated by Django 4.1.7 on 2023-04-20 23:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0025_alter_program_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='date',
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_date', models.DateTimeField(default=datetime.datetime(2023, 4, 21, 1, 22, 35, 956314))),
                ('concert_pianist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('concert_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.program')),
            ],
        ),
    ]
