# Generated by Django 4.1.7 on 2023-04-22 22:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_concert_concert_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['concert_date']},
        ),
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 0, 32, 16, 871460)),
        ),
        migrations.AlterField(
            model_name='concert',
            name='concert_pianist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pianist'),
        ),
    ]
