# Generated by Django 4.1.7 on 2023-04-23 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_concert_concert_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 10, 3, 11, 222210)),
        ),
    ]
