# Generated by Django 4.1.7 on 2023-04-29 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_remove_systemmessage_room_remove_systemmessage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 20, 30, 57, 140547), unique=True),
        ),
    ]
