# Generated by Django 4.2 on 2023-04-30 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_concert_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 0, 17, 36, 770371), unique=True),
        ),
    ]
