# Generated by Django 4.2 on 2023-05-01 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_concert_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 22, 49, 42, 197150), unique=True),
        ),
    ]
